var x=10
if(x<20)
{
    console.log("x is less than 20")
}
else
{
    console.log("x is greater than 20")
}

var a=31
if(a%2==0)
{
    console.log("a is even")
}
else {
    console.log("a is odd")
}
for(i=1;i<=100;i++)
if(i%2==1)
{
    
    console.log(i)
}
i=1
while(i<=100)
{
    console.log(i);
    i++;
}
var num=521;
var rev=0;
while(num>0)
{
    rem=num%10;
    rev=rev*10+rem;
    num=parseInt(num/10);

}

console.log(rev)






